# Generated by Django 5.2.8 on 2025-11-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120)),
                ('metin', models.TextField()),
                ('yayimlanma_tarihi', models.DateTimeField()),
            ],
        ),
    ]
