# Generated by Django 5.2.8 on 2025-11-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_baslik_alter_post_metin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='yayimlanma_tarihi',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Published Date'),
        ),
    ]
