# Generated by Django 5.2.8 on 2025-11-17 16:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='metin',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
        ),
    ]
